blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create_article'),
    path('blog/', ArticleListView.as_view(), name='blog'),
    path('view/<slug:slug>/', never_cache(ArticleDetailView.as_view()), name='view_article'),
    path('edit/<slug:slug>/', never_cache(ArticleUpdateView.as_view()), name='edit_article'),
    path('delete/<slug:slug>/', never_cache(ArticleDeleteView.as_view()), name='delete_article'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('contacts/', include('catalog.urls', namespace='contact')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from pytils.translit import slugify


NULLABLE = {
    'blank': True, 'null': True
}


class Article(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.CharField(max_length=250, unique=True, db_index=True, verbose_name='url')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog_img/', **NULLABLE, verbose_name='Фото')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    views = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'
        ordering = ('title', 'created_at', 'is_published',)

blog/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Article
from catalog.forms import ArticleForm


class ArticleCreateView(PermissionRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('blog:blog')
    permission_required = 'blog.add_article'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание статьи'
        return context


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('blog:view_article')
    permission_required = 'blog.change_article'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование статьи'
        return context

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return redirect(reverse('blog:view_article', args=[self.kwargs.get('slug')]))


class ArticleListView(ListView):
    paginate_by = 6
    model = Article
    extra_context = {'title': 'Блог: статьи'}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True).order_by('-created_at')
        return queryset


class ArticleDetailView(DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = str(context['object'])
        return context

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views += 1
        obj.save()
        return obj


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('blog:blog')
    permission_required = 'blog.delete_article'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Удаление "{self.object.title}"'
        return context

blog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>Удалить пост {{ object.title }}?</p>
                    <button type="submit" class="btn btn-block btn-outline-danger">Подтвердить</button>
                    <a href="{% url 'blog:view_article' object.slug %}" class="p-2 btn btn-outline-primary">Отменить</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}
{% load media_tag %}
{% load static %}

{% block content %}
    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            {% if object.preview %}
                <img src="{% mediapath object.preview %}" alt="{{ object }}"/>
            {% else %}
                <img src="{% static 'img/default.jpg' %}" alt="{{ object }}"/>
            {% endif %}
        </div>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <small class="d-block mb-3 text-muted">Просмотров: {{ object.views }}</small>
                <p>
                    {{ object.content }}
                </p>
            </div>
        </div>
        <p>
            {% if perms.blog.change_article %}
            <a href="{% url 'blog:edit_article' object.slug %}"
               class="m-1 btn btn-sm btn-outline-warning">Редактировать статью
            </a>
            {% endif %}
            {% if perms.blog.delete_article %}
            <a href="{% url 'blog:delete_article' object.slug %}"
               class="m-1 btn btn-sm btn-outline-danger">Удалить статью
            </a>
            {% endif %}
        </p>
    </div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-warning">
                        {% if object %}
                            Сохранить изменения
                        {% else %}
                            Создать материал
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_list.html
{%  extends 'catalog/base.html' %}
{% load static %}
{% load media_tag %}

{% block content %}
        {% if perms.blog.change_article %}
        <div class="col-12 mb-4">
            <a class="p-2 btn btn-outline-warning" href="{% url 'blog:create_article' %}">Добавить статью</a>
        </div>
        {% endif %}
        {% for object in object_list %}
            <div class="col-12 col-sm-6 col-md-4 mb-5">
                <div class="post-entry">
                    <a href="{% url 'blog:view_article' object.slug %}" class="post-thumbnail">
                        {% if object.preview %}
                            <img src="{% mediapath object.preview %}" alt="{{ object }}" class="img-fluid"/>
                        {% else %}
                            <img src="{% static 'img/default.jpg' %}" alt="{{ object }}" class="img-fluid"/>
                        {% endif %}
                    </a>
                    <div class="post-content-entry">
                        <h3><a href="{% url 'blog:view_article' object.slug %}">{{ object }}</a></h3>
                        <p>{{ object.content|truncatechars:100 }}</p>
                        <div class="meta">
                            <span>by <strong>Admin</strong></span> <span>on <strong>{{ object.created_at }}</strong></span>
                        </div>
                    </div>
                </div>
            </div>
        {%  endfor %}

    {% include 'catalog/includes/inc_pagination.html' %}

{% endblock %}