blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create_article'),
    path('blog/', ArticleListView.as_view(), name='blog'),
    path('view/<slug:slug>/', never_cache(ArticleDetailView.as_view()), name='view_article'),
    path('edit/<slug:slug>/', never_cache(ArticleUpdateView.as_view()), name='edit_article'),
    path('delete/<slug:slug>/', never_cache(ArticleDeleteView.as_view()), name='delete_article'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ContactListView, CategoryListView, CategoryCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', ContactListView.as_view(), name='contacts'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('category_list/create/', CategoryCreateView.as_view(), name='create_category'),
    path('products/', ProductListView.as_view(), name='products'),
    path('item/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='item'),
    path('create_item/', never_cache(ProductCreateView.as_view()), name='item_create'),
    path('update_item/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='item_update'),
    path('delete_item/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='item_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('contacts/', include('catalog.urls', namespace='contact')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('activate-user/<str:token>/', VerifyEmailView.as_view(), name='activate_user'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('password-reset-sent/', PasswordResetSentView.as_view(), name='password-reset-sent'),
    path('<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=250, **NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Продукт')
    description = models.TextField(max_length=250, **NULLABLE, verbose_name='Описание')
    photo = models.ImageField(upload_to='photos/', **NULLABLE, verbose_name='Фото')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена', default=0.0)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='продавец')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['pk']
        permissions = [
            ('set_is_published', 'Может публиковать товары'),
            ('set_description', 'Может изменять описание товара'),
            ('set_category', 'Может изменять категорию товара'),
        ]


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.EmailField(verbose_name='Email')
    phone = models.CharField(**NULLABLE, max_length=100, verbose_name='Телефон')
    textarea = models.TextField(**NULLABLE, verbose_name='Сообщение')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.PositiveIntegerField(verbose_name='Номер версии')
    title = models.CharField(max_length=30, **NULLABLE, verbose_name='Название версии')
    is_actual = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return str(self.number)

    class Meta:
        verbose_name = 'Версию'
        verbose_name_plural = 'Версии'
        ordering = ['number']

catalog/forms.py
from django import forms

from blog.models import Article
from catalog.models import Product, Version, Category


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.ChoiceField):
                field.widget.attrs['class'] = 'form-select'
            elif isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    RESTRICTED_WORDS = [
        'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
        'дёшево', 'бесплатно', 'обман', 'полиция', 'радар'
    ]

    class Meta:
        model = Product
        fields = '__all__'

    def restrict_words(self, title):
        for word in self.RESTRICTED_WORDS:
            if word.lower() in title.lower():
                raise forms.ValidationError(f'Недопустимое слово "{word}"')

    def clean_name(self):
        cleaned_data = (self.cleaned_data.get('name'))
        self.restrict_words(cleaned_data)
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        self.restrict_words(cleaned_data)
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ArticleForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'preview', 'is_published',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm, CategoryForm
from catalog.models import Product, Contact, Version, Category
from catalog.services import get_cache_for_categories


class ProductListView(ListView):
    paginate_by = 6
    model = Product
    template_name = 'catalog/index.html'
    ordering = ['-pk']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Каталог товаров'
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.user.is_authenticated and not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user).order_by('-time_create')
        elif not self.request.user.is_authenticated:
            queryset = queryset.filter(is_published=True).order_by('-time_update')
        return queryset


class ProductCategoryListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        category_pk = self.kwargs['pk']
        return Product.objects.filter(category_id=category_pk)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/item.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = str(context['object'])
        context['version'] = Version.objects.filter(product=self.kwargs['pk'], is_actual=True).order_by('-pk')
        return context


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.add_product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание товара'
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context['formset'] = VersionFormset(self.request.POST)
        else:
            context['formset'] = VersionFormset()
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'

    def get_success_url(self):
        return reverse('catalog:item', kwargs={'pk': self.object.pk})

    def get_form(self, form_class=None):

        form = super().get_form(form_class)
        if self.object.owner != self.request.user:
            product_fields = [field_key for field_key in form.fields.keys()]
            for field in product_fields:
                if not self.request.user.has_perms([f'catalog.set_{field}']):
                    del form.fields[field]
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменение товара'
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
            if self.request.method == 'POST':
                context['formset'] = VersionFormset(self.request.POST, instance=self.object)
            else:
                context['formset'] = VersionFormset(instance=self.object)
        return context

    def form_valid(self, form):
        formset = self.get_context_data().get('formset')
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            if formset.is_valid():
                actual_version_count = 0
                for f in formset:
                    if f.cleaned_data.get('is_actual'):
                        actual_version_count += 1
                        if actual_version_count > 1:
                            form.add_error(None, "Вы можете выбрать только одну активную версию")
                            return self.form_invalid(form=form)
                formset.save()
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()
        return (obj.owner == self.request.user
                or self.request.user.has_perms(('catalog.change_product',))
                or self.request.user.is_superuser)

    def handle_no_permission(self):
        raise Http404('У вас нет прав для изменения этого товара')


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.delete_product'


class ContactListView(ListView):
    model = Contact
    template_name = 'catalog/contacts.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Контакты'
        return context


class CategoryCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    permission_required = 'catalog.add_category'
    success_url = reverse_lazy("catalog:category_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание категории'
        return context


class CategoryListView(ListView):
    paginate_by = 6
    model = Category
    template_name = 'catalog/category_list.html'
    ordering = ['-pk']

    def get_queryset(self):
        return get_cache_for_categories(Category)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории товаров'
        return context

catalog/templates/catalog/includes/inc_footer.html
{% load static %}
<!-- Start Footer Section -->
<footer class="footer-section">
    <div class="container relative">
        <div class="row g-5 mb-5">
            <div class="col-lg-6">
                <div class="col-6 col-sm-6 col-md-6">
                    <div class="mb-4 footer-logo-wrap"><a href="#" class="footer-logo">Furni<span>.</span></a></div>
                    <p class="mb-4">В Furni мы верим, что мебель должна не только служить функциональным целям, но и приносить радость и уют в каждый дом.
                    Мы стремимся к инновациям в дизайне, используя только высококачественные материалы, чтобы создавать предметы, которые превосходят ожидания наших клиентов.</p>
                </div>
                <div class="col-6 col-sm-6 col-md-6">
                    <ul class="list-unstyled custom-social">
                        <li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
                        <li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
                        <li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
                        <li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="row links-wrap">
                    <div class="col-6 col-sm-6 col-md-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Главная</a></li>
                            <li><a href="#">Услуги</a></li>
                            <li><a href="#">Блог</a></li>
                            <li><a href="#">Контакты</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-sm-6 col-md-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Вакансии</a></li>
                            <li><a href="#">Наша команда</a></li>
                            <li><a href="#">Наша история</a></li>
                            <li><a href="#">Лидеры продаж</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="border-top copyright">
            <div class="row pt-4">
                <div class="col-lg-6">
                    <p class="mb-2 text-center text-lg-start">Copyright &copy;{% now 'Y' %}
                        Все права защищены
                    </p>
                </div>
                <div class="col-lg-6 text-center text-lg-end">
                    <ul class="list-unstyled d-inline-flex ms-auto">
                        <li><a href="#">Политика конфиденциальности</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/tiny-slider.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

catalog/templates/catalog/includes/inc_header.html
{% load static %}
<!-- Start Header/Navigation -->
<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'catalog:index' %}">Furni<span>.</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsFurni">
            <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
                <li class="nav-item active"><a class="nav-link" href="{% url 'catalog:index' %}">Главная</a></li>
                <li><a class="nav-link" href="{% url 'catalog:category_list' %}">Категории</a></li>
                <li><a class="nav-link" href="#">О нас</a></li>
                <li><a class="nav-link" href="#">Услуги</a></li>
                <li><a class="nav-link" href="{% url 'blog:blog' %}">Блог</a></li>
                <li><a class="nav-link" href="{% url 'catalog:contacts' %}">Контакты</a></li>
            </ul>
            <ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
                <!-- <li><a class="nav-link" href="#"><img src="{% static 'img/user.svg' %}"></a></li>
                <li><a class="nav-link" href="#"><img src="{% static 'img/cart.svg' %}"></a></li> -->
                <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                    {% if user.is_authenticated %}
                        {% if user.first_name %}
                            <small class="text-white mt-1 me-2 py-2">Привет, {{ user.first_name }}!</small>
                        {% endif %}
                        <a class="text-muted mt-1 me-2 py-2" href="{% url 'users:profile' %}">Профиль</a>
                        <a class="text-muted mt-1 me-2 py-2" href="{% url 'users:logout' %}">Выйти</a>
                    {% else %}
                        <a class="text-white mt-1 me-2 py-2" href="{% url 'users:login' %}">Войти</a>
                        <a class="text-white mt-1 me-2 py-2" href="{% url 'users:register' %}">Регистрация</a>
                    {% endif %}
                </nav>
            </ul>
        </div>
    </div>
</nav>

catalog/templates/catalog/includes/inc_item.html
{% load static %}
{% load media_tag %}

<div class="col-12 col-md-4 col-lg-4 mb-5 mb-md-0">
    <a class="product-item" href="{% url 'catalog:item' object.pk %}">
        <img src="{% mediapath object.photo %}" alt="{{ object }}" class="img-fluid product-thumbnail">
        <h3 class="product-title">{{ object.name }}</h3>
        <p class="product-description px-5">{{ object.description|truncatechars:100 }}</p>
        <span class="icon-cross">
            <img src="{% static 'img/cross.svg' %}" class="img-fluid">
        </span>
    </a>
</div>

catalog/templates/catalog/includes/inc_pagination.html
<div class="col-12">
    <div class="text-center mt-5">
        {% if page_obj.has_previous %}
            <a class="btn btn-primary d-inline-flex align-items-center"
               href="?page=1">&laquo; Первая</a>
            <a class="btn btn-primary d-inline-flex align-items-center"
               href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}
        {% if page_obj.has_next %}
            <a class="btn btn-primary d-inline-flex align-items-center"
               href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a class="btn btn-primary d-inline-flex align-items-center"
               href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </div>
</div>