blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create_article'),
    path('blog/', ArticleListView.as_view(), name='blog'),
    path('view/<slug:slug>/', never_cache(ArticleDetailView.as_view()), name='view_article'),
    path('edit/<slug:slug>/', never_cache(ArticleUpdateView.as_view()), name='edit_article'),
    path('delete/<slug:slug>/', never_cache(ArticleDeleteView.as_view()), name='delete_article'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ContactListView, CategoryListView, CategoryCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', ContactListView.as_view(), name='contacts'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('category_list/create/', CategoryCreateView.as_view(), name='create_category'),
    path('products/', ProductListView.as_view(), name='products'),
    path('item/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='item'),
    path('create_item/', never_cache(ProductCreateView.as_view()), name='item_create'),
    path('update_item/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='item_update'),
    path('delete_item/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='item_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('contacts/', include('catalog.urls', namespace='contact')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('activate-user/<str:token>/', VerifyEmailView.as_view(), name='activate_user'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('password-reset-sent/', PasswordResetSentView.as_view(), name='password-reset-sent'),
    path('<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='email')
    phone = models.CharField(max_length=50, **NULLABLE, verbose_name='Номер телефона')
    country = models.CharField(max_length=50, **NULLABLE, verbose_name='Страна')
    avatar = models.ImageField(upload_to='media/users/', **NULLABLE, verbose_name='Аватар')
    is_active = models.BooleanField(default=False, verbose_name='Статус активности')

    email_verificator = models.CharField(max_length=30, **NULLABLE, verbose_name='код верификации почты')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ('country', 'is_active')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm, \
    UserChangeForm

from catalog.forms import StyleFormMixin
from users.models import User


class StylePasswordResetMixin:
    """
   Обновление стилей форм восстановления пароля
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control mt-2',
                'autocomplete': 'off'
            })


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    """
    Форма авторизации на сайте
    """
    pass


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """
    Форма регистрации на сайте
    """

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserForgotPasswordForm(StylePasswordResetMixin, PasswordResetForm):
    """
    Запрос на восстановление пароля
    """
    pass


class UserSetNewPasswordForm(StylePasswordResetMixin, SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """
    pass


class UserProfileForm(StyleFormMixin, UserChangeForm):
    """
     Форма обновления данных пользователя
     """

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'phone', 'country',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import os
import random
import string

from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, TemplateView, UpdateView

from users.forms import UserRegisterForm, UserLoginForm, UserForgotPasswordForm, UserSetNewPasswordForm, UserProfileForm
from users.models import User


class UserLoginView(LoginView):
    """
    Представление авторизация на сайте
    """
    form_class = UserLoginForm
    template_name = 'users/login.html'
    next_page = 'catalog:index'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация на сайте'
        return context


class RegisterView(CreateView):
    """
    Представление регистрации на сайте с формой регистрации
    """
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:email_confirmation_sent')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        new_user = form.save()
        # Создаем и сохраняем токен подтверждения
        token = ''.join(random.choices(string.ascii_letters + string.digits, k=25))
        new_user.email_verificator = token
        new_user.save()
        # Отправляем письмо с подтверждением
        current_site = get_current_site(self.request)
        mail_subject = 'Conrirm registration'
        message = render_to_string(
            'users/email_check.html',
            {
                'domain': current_site.domain,
                'token': token,
            },
        )
        send_mail(mail_subject, message, os.getenv('EMAIL_HOST_USER'), [new_user.email])
        return response


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class VerifyEmailView(View):
    """
    Представление верификации нового пользователя по почте
    """

    def get(self, request, token):
        try:
            user = User.objects.get(email_verificator=token)
            user.is_active = True
            user.save()
            return redirect('users:email_confirmed')
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            return redirect('users:email_confirmation_failed')


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


class UserForgotPasswordView(PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """
    form_class = UserForgotPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:password-reset-sent')
    subject_template_name = 'users/password_subject_reset_mail.txt'
    email_template_name = 'users/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на сброс пароля'
        return context


class PasswordResetSentView(TemplateView):
    template_name = 'users/password_reset_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо отправлено'
        return context


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """
    form_class = UserSetNewPasswordForm
    template_name = 'users/user_password_set_new.html'
    success_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context


class ProfileView(UpdateView):
    """
    Представление редактирования профиля
    """
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('catalog:index')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        return context

users/templates/users/email_check.html
{% autoescape off %}
Здравствуйте!
Вы или кто-то другой указали этот email для регистрации на сайте http://{{ domain }}.
Если это были вы, пожалуйста, пройдите по ссылке ниже для подтверждения регистрации:
http://{{ domain }}{% url 'users:activate_user' token=token %}
{% endautoescape %}

users/templates/users/email_confirmation_failed.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
    <p>
        Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек.
        Пожалуйста, <a href="{% url 'users:register' %}">зарегистрируйтесь</a> снова.
    </p>
</div>

{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
    <p>
      На ваш адрес электронной почты было отправлено письмо с подтверждением.
      Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.<br />
      Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию!</p>
    <p><a href="{% url 'users:login' %}">Перейти на форму авторизации</a></p>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="form-control p-2 btn btn-outline-warning">Войти</button>
                </div>
                <div class="card-footer"><a href="#{# {% url 'users:password_reset' %} #}">Забыли пароль?</a></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_mail.html
{% autoescape off %}
    Вы получили это электронное письмо, потому что запросили сброс пароля для своей учетной записи пользователя на {{ site_name }}.

	Перейдите на следующую страницу и выберите новый пароль:
	{% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
{% endautoescape %}

users/templates/users/password_reset_sent.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо восстановления отправлено!</h4>
    <p>
      На ваш адрес электронной почты было отправлено письмо со ссылкой на восстановление пароля.
      Пожалуйста, проверьте свою электронную почту и нажмите на ссылку, чтобы восстановить пароль.<br />
      Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="form-control p-2 btn btn-outline-warning">Зарегистрироваться</button>
                </div>
            </div>
            <a href="{% url 'catalog:index' %}" class="align-content-start p-2 btn btn-success">На главную</a>
        </div>
    </form>

</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="form-control p-2 btn btn-outline-warning">Сохранить</button>
                </div>
                <div class="card-footer"><a href="{% url 'users:password_reset' %}">Сменить пароль</a></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="form-control p-2 btn btn-outline-warning">Восстановить пароль</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="form-control p-2 btn btn-outline-warning">Подтвердить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}