blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create_article'),
    path('blog/', ArticleListView.as_view(), name='blog'),
    path('view/<slug:slug>/', never_cache(ArticleDetailView.as_view()), name='view_article'),
    path('edit/<slug:slug>/', never_cache(ArticleUpdateView.as_view()), name='edit_article'),
    path('delete/<slug:slug>/', never_cache(ArticleDeleteView.as_view()), name='delete_article'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ContactListView, CategoryListView, CategoryCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', ContactListView.as_view(), name='contacts'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('category_list/create/', CategoryCreateView.as_view(), name='create_category'),
    path('products/', ProductListView.as_view(), name='products'),
    path('item/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='item'),
    path('create_item/', never_cache(ProductCreateView.as_view()), name='item_create'),
    path('update_item/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='item_update'),
    path('delete_item/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='item_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('contacts/', include('catalog.urls', namespace='contact')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=250, **NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Продукт')
    description = models.TextField(max_length=250, **NULLABLE, verbose_name='Описание')
    photo = models.ImageField(upload_to='photos/', **NULLABLE, verbose_name='Фото')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена', default=0.0)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='продавец')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['pk']
        permissions = [
            ('set_is_published', 'Может публиковать товары'),
            ('set_description', 'Может изменять описание товара'),
            ('set_category', 'Может изменять категорию товара'),
        ]


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.EmailField(verbose_name='Email')
    phone = models.CharField(**NULLABLE, max_length=100, verbose_name='Телефон')
    textarea = models.TextField(**NULLABLE, verbose_name='Сообщение')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.PositiveIntegerField(verbose_name='Номер версии')
    title = models.CharField(max_length=30, **NULLABLE, verbose_name='Название версии')
    is_actual = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return str(self.number)

    class Meta:
        verbose_name = 'Версию'
        verbose_name_plural = 'Версии'
        ordering = ['number']

catalog/forms.py
from django import forms

from blog.models import Article
from catalog.models import Product, Version, Category


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.ChoiceField):
                field.widget.attrs['class'] = 'form-select'
            elif isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    RESTRICTED_WORDS = [
        'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
        'дёшево', 'бесплатно', 'обман', 'полиция', 'радар'
    ]

    class Meta:
        model = Product
        fields = '__all__'

    def restrict_words(self, title):
        for word in self.RESTRICTED_WORDS:
            if word.lower() in title.lower():
                raise forms.ValidationError(f'Недопустимое слово "{word}"')

    def clean_name(self):
        cleaned_data = (self.cleaned_data.get('name'))
        self.restrict_words(cleaned_data)
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        self.restrict_words(cleaned_data)
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ArticleForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'preview', 'is_published',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm, CategoryForm
from catalog.models import Product, Contact, Version, Category
from catalog.services import get_cache_for_categories


class ProductListView(ListView):
    paginate_by = 6
    model = Product
    template_name = 'catalog/index.html'
    ordering = ['-pk']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Каталог товаров'
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.user.is_authenticated and not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user).order_by('-time_create')
        elif not self.request.user.is_authenticated:
            queryset = queryset.filter(is_published=True).order_by('-time_update')
        return queryset


class ProductCategoryListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        category_pk = self.kwargs['pk']
        return Product.objects.filter(category_id=category_pk)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/item.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = str(context['object'])
        context['version'] = Version.objects.filter(product=self.kwargs['pk'], is_actual=True).order_by('-pk')
        return context


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.add_product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание товара'
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context['formset'] = VersionFormset(self.request.POST)
        else:
            context['formset'] = VersionFormset()
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'

    def get_success_url(self):
        return reverse('catalog:item', kwargs={'pk': self.object.pk})

    def get_form(self, form_class=None):

        form = super().get_form(form_class)
        if self.object.owner != self.request.user:
            product_fields = [field_key for field_key in form.fields.keys()]
            for field in product_fields:
                if not self.request.user.has_perms([f'catalog.set_{field}']):
                    del form.fields[field]
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменение товара'
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
            if self.request.method == 'POST':
                context['formset'] = VersionFormset(self.request.POST, instance=self.object)
            else:
                context['formset'] = VersionFormset(instance=self.object)
        return context

    def form_valid(self, form):
        formset = self.get_context_data().get('formset')
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            if formset.is_valid():
                actual_version_count = 0
                for f in formset:
                    if f.cleaned_data.get('is_actual'):
                        actual_version_count += 1
                        if actual_version_count > 1:
                            form.add_error(None, "Вы можете выбрать только одну активную версию")
                            return self.form_invalid(form=form)
                formset.save()
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()
        return (obj.owner == self.request.user
                or self.request.user.has_perms(('catalog.change_product',))
                or self.request.user.is_superuser)

    def handle_no_permission(self):
        raise Http404('У вас нет прав для изменения этого товара')


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.delete_product'


class ContactListView(ListView):
    model = Contact
    template_name = 'catalog/contacts.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Контакты'
        return context


class CategoryCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    permission_required = 'catalog.add_category'
    success_url = reverse_lazy("catalog:category_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание категории'
        return context


class CategoryListView(ListView):
    paginate_by = 6
    model = Category
    template_name = 'catalog/category_list.html'
    ordering = ['-pk']

    def get_queryset(self):
        return get_cache_for_categories(Category)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории товаров'
        return context

catalog/templates/catalog/base.html
{% load static %}
{% load media_tag %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="favicon.png">

    <meta name="description" content=""/>
    <meta name="keywords" content=""/>

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="{% static '/css/tiny-slider.css' %}" rel="stylesheet">
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
    <title>{{ title }}</title>
</head>

<body>
    {% include 'catalog/includes/inc_header.html' %}
    <!-- Start Hero Section -->
    <div class="hero">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5">
                    <div class="intro-excerpt">
                        <h1>{{ title }}</h1>
                        <p class="mb-4">Лучшая мебель для Вашей комфортной жизни</p>
                        <p><a href="#" class="btn btn-white-outline">Посмотреть</a></p>
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="hero-img-wrap">
                        <img src="{% static 'img/couch.png' %}" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Hero Section -->

    <!-- Start Product Section -->
    <div class="product-section">
        <div class="container">
            <div class="row">

                {% block content %}

                {% endblock %}

            </div>
        </div>
    </div>
    <!-- End Product Section -->

    {% include 'catalog/includes/inc_footer.html' %}

</body>

</html>

catalog/templates/catalog/category_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="p-2 btn btn-outline-warning form-control">
                            {% if object %}
                                Сохранить изменения
                            {% else %}
                                Создать категорию
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
            {% if formset %}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                                <hr class="m-4"/>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load media_tag %}
{% block content %}
<div class="col-12 mb-5">
    {% if perms.catalog.add_category %}
    <a class="btn btn-info" href="{% url 'catalog:create_category' %}">Добавить категорию</a>
    {% endif %}
</div>
{% for object in object_list %}
    {% if object.is_published or user.is_staff or user.is_superuser %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">Категория: {{ object.name }}</p>
                <p>Описание: {{ object.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="#" class="btn btn-sm btn-info">Посмотреть</a>
                    </div>
                    <small class="text-muted"></small>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endfor %}
{%  endblock %}

catalog/templates/catalog/contacts.html
{%  extends 'catalog/base.html' %}

{% block content %}

<!-- Start Contact Form -->
<div class="untree_co-section">
    <div class="container">
        <div class="block">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-8 pb-4">
                    {% for object in object_list %}
                    <div class="row mb-5">
                        <div class="col-lg-4">
                            <div class="service no-shadow align-items-center link horizontal d-flex active" data-aos="fade-left"
                                 data-aos-delay="0">
                                <div class="service-icon color-1 mb-4">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
                                    </svg>
                                </div> <!-- /.icon -->
                                <div class="service-contents">
                                    <p>{{ object.name }}</p>
                                </div> <!-- /.service-contents-->
                            </div> <!-- /.service -->
                        </div>
                        <div class="col-lg-4">
                            <div class="service no-shadow align-items-center link horizontal d-flex active" data-aos="fade-left"
                                 data-aos-delay="0">
                                <div class="service-icon color-1 mb-4">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-envelope-fill" viewBox="0 0 16 16">
                                        <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                                    </svg>
                                </div> <!-- /.icon -->
                                <div class="service-contents">
                                    <p>{{ object.email }}</p>
                                </div> <!-- /.service-contents-->
                            </div> <!-- /.service -->
                        </div>
                        <div class="col-lg-4">
                            <div class="service no-shadow align-items-center link horizontal d-flex active" data-aos="fade-left"
                                 data-aos-delay="0">
                                <div class="service-icon color-1 mb-4">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-telephone-fill" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                              d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                                    </svg>
                                </div> <!-- /.icon -->
                                <div class="service-contents">
                                    <p>{{ object.phone }}</p>
                                </div> <!-- /.service-contents-->
                            </div> <!-- /.service -->
                        </div>
                    </div>
                    {% endfor %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label class="text-black" for="fname">Ваше имя</label>
                                    <input type="text" class="form-control" id="fname">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="text-black" for="email">Ваш email</label>
                            <input type="email" class="form-control" id="email">
                        </div>
                        <div class="form-group mb-5">
                            <label class="text-black" for="message">Сообщение</label>
                            <textarea name="" class="form-control" id="message" cols="30" rows="5"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary-hover-outline">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- End Contact Form -->

{% endblock %}

</body>

</html>

catalog/templates/catalog/index.html
{%  extends 'catalog/base.html' %}
{% load static %}
{% load media_tag %}

{% block content %}
    {% if user.is_authenticated %}
        {% if perms.catalog.change_product %}
            <div class="col-12 mb-5">
                <a class="btn btn-outline-primary" href="{% url 'catalog:item_create' %}">Добавить модель</a>
            </div>
        {% endif %}
    {% endif %}
    {% for object in object_list %}
        {% if object.is_published or user.is_staff or user.is_superuser %}
        <div class="col-12 col-md-4 col-lg-4 mb-5 mb-md-0">
            <a class="product-item" href="{% url 'catalog:item' object.pk %}">
                <img src="{% mediapath object.photo %}" alt="{{ object }}" class="img-fluid product-thumbnail">
                <h3 class="product-title">{{ object.name }}</h3>
                <p class="product-description px-5">{{ object.description|truncatechars:100 }}</p>
                <span class="icon-cross">
                    <img src="{% static 'img/cross.svg' %}" class="img-fluid">
                </span>
            </a>
        </div>
        {% endif %}
    {%  endfor %}
    {% include 'catalog/includes/inc_pagination.html' %}

{% endblock %}

catalog/templates/catalog/item.html
{% extends 'catalog/base.html' %}
{% load media_tag %}
{% load static %}

{% block content %}
    <div class="col-12 col-md-6 col-lg-6 mb-5 mb-md-0">
        <div class="product-item-inner">
            {% if object.photo %}
                <img src="{% mediapath object.photo %}" alt="{{ object }}"/>
            {% else %}
                <img src="{% static 'img/product-1.png.png' %}" alt="{{ object }}"/>
            {% endif %}
        </div>
    </div>
    <div class="col-12 col-md-6 col-lg-6 mb-5 mb-md-0">
        <div class="product-item-inner">

            <h3 class="product-description m-5">{{ object.name }}</h3>
            <p class="product-description px-5">{{ object.category }}</p>
            <p class="product-description px-5">{{ object.category.description }}</p>
            <p class="product-description px-5">{{ object.description }}</p>
            <p class="product-description px-5">{{ object.price }}</p>
            <p class="product-description px-5">{{ object.owner|default:'Furni' }}</p>
            {% if version %}
                <small class="d-block mb-3 text-muted">Актуальная версия:
                    <!--uncomment cycle and separator if more than one actual version available-->
                    <!--{% for v in version %}-->
                        {{ v.number }}
                        {% if v.title %}
                            &laquo;{{ v.title }}&raquo;
                        {% endif %}
                        <!--{% if not forloop.last %}|{% endif %}-->
                        <!--{% endfor %}-->
                </small>
            {% endif %}
            {% if user.is_authenticated %}
                {% if perms.catalog.change_product or user == object.owner %}
                <a href="{% url 'catalog:item_update' object.pk %}"
                   class="m-1 btn btn-sm btn-outline-warning">Редактировать товар</a>
                {% endif %}
                {% if user.is_superuser or user == object.owner %}
                <a href="{% url 'catalog:item_delete' object.pk %}"
                   class="m-1 btn btn-sm btn-outline-danger">Удалить товар</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>Удалить пост {{ object.title }}?</p>
                    <button type="submit" class="p-2 btn btn-outline-danger">Подтвердить</button>
                    <a href="{% url 'catalog:item' object.pk %}" class="p-2 btn btn-outline-primary">Отменить</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="p-2 btn btn-outline-warning form-control">
                            {% if object %}
                                Сохранить изменения
                            {% else %}
                                Создать продукт
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
            {% if formset %}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                                <hr class="m-4"/>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{%  extends 'catalog/base.html' %}
{% load static %}
{% load media_tag %}

{% block content %}
    {% if user.is_authenticated %}
        {% if perms.catalog.change_product %}
            <div class="col-12 mb-5">
                <a class="btn btn-outline-primary" href="{% url 'catalog:item_create' %}">Добавить модель</a>
            </div>
        {% endif %}
    {% endif %}
    {% for object in object_list %}
        <div class="col-12 col-md-4 col-lg-4 mb-5 mb-md-0">
            <a class="product-item" href="{% url 'catalog:item' object.pk %}">
                <img src="{% mediapath object.photo %}" alt="{{ object }}" class="img-fluid product-thumbnail">
                <h3 class="product-title">{{ object.name }}</h3>
                <p class="product-description px-5">{{ object.description|truncatechars:100 }}</p>
                <span class="icon-cross">
                    <img src="{% static 'img/cross.svg' %}" class="img-fluid">
                </span>
            </a>
        </div>
    {%  endfor %}
    {% include 'catalog/includes/inc_pagination.html' %}

{% endblock %}